### PR TITLE
Breaking rules by packs

### PR DESCRIPTION
**Pull request by emedvedev**
It would be best to merge this after the icons PR and not before.

### CODE REVIEW

**Comment by enykeev** [comment]
Ok, several problems:
- whitespaces. Line should not end on whitespace character which includes an empty line always having 0 length. Bonus points for editor config so we don't have to return to that ever again =)
- catch promises. Otherwise, the errors will go unnoticed.
- bump st2client.js to 0.3.6 so we would know this PR depends on the newer version of st2client and also requires user to make `npm install` again
- just a hint, `img:not([src])` is the selector you can probably make use of

**Comment by enykeev** [comment]
this feedback is also related to #182

**Comment by emedvedev** [comment]
Should be better now, fixed everything. I liked the `[src]` setup, but it's more readable with `:not`, you're right. :)
#182 can be left as is (or even closed), this PR merges that branch anyway.

**Comment by enykeev** [comment]
LGTM, although, lets wait with merging until I publish 0.3.6. What to do with #182 is up to you to decide.

**Comment by emedvedev** [comment]
Ok, I'll leave you to it. Merge whenever you're ready

**Pull request merged**
