### PR TITLE
Added include_attributes query parameter for executions API

### PR DESCRIPTION
**Pull request by VineeshJain**
Removed the exclude_attributes=trigger_instance query parameter and introduced the include_attributes parameter. The attributes to be included in the response are:

- status
- start_timestamp
- result
- runner
- parameters

This enhancement is for the Actions --> Executions screen

image

### CODE REVIEW

**Comment by Kami** [comment]
LGTM :+1: 

(still need to test it though)

**Comment by Kami** [comment]
Do we plan to do the same for execution detail view tab on execution history page (IIRC, we already do it for the main execution history view, but not when you click on a particular execution - https://github.com/StackStorm/st2web/pull/605/files)?

**Comment by VineeshJain** [comment]
Yes, absolutely, I am currently working on making enhancements to the execution details API only.

**Comment by Kami** [comment]
Looks like this didn't make it into v3.0.0. I will re-tag it as v3.0.1 and hopefully we can get it finished and merged soon :)

**Comment by armab** [comment]
@VineeshJain To close the loop, is this PR ready to merge or there anything yet missing?

**Comment by VineeshJain** [comment]
Closing this PR without merging. This work in not to be merged as after talking to the Lindsay it was decided that the `trigger_instance` data is still needed in the code view of the UI. Excluding the `trigger_instance` query parameter also excludes it from the code view. Hence, this work is discarded.

**Pull request closed without merging**
