### PR TITLE
Add trace tag support

### PR DESCRIPTION
**Pull request by enykeev**

### CODE REVIEW

**Comment by enykeev** [comment]
@manasdk anything else is missing? Not really aware of the scope of this thing.
@emedvedev remind me why we choose to make selectable field as input?

**Comment by emedvedev** [comment]
No idea, I think it happened before me. Maybe it's easier to style or there was a ready-made Angular directive or something?

**Comment by enykeev** [comment]
@emedvedev https://github.com/StackStorm/st2web/commit/3eebb1fc743480b2cb45345bf0ba4149301e7ad5

**Comment by emedvedev** [comment]
Ah, this field! Afair some browsers don't support selecting text in anything but inputs.

**Comment by manasdk** [comment]
:+1:

**Comment by dzimine** [comment]
+1

**Pull request merged**
