### PR TITLE
Showing pack name and icon in rule details

### PR DESCRIPTION
**Pull request by emedvedev**

### CODE REVIEW

**Comment by Kami** [comment]
Screenshot would be nice.

In any case:

**Comment by emedvedev** [comment]
buu6cual-zbckorjod-k_0vhwqkoc3ok1unchevs3w0

**Comment by emedvedev** [comment]
Removed "pack" The reason why I didn't put it on the top right is that the rule name is actually supposed to be there, so we want to save that space. In the screenshot above it's not shown because the name is simply too long.

**Comment by dzimine** [comment]
Ed, Gilberto is doing a full-redesign of the rule view, just be aware.

**Comment by emedvedev** [comment]
Then I'll just go ahead and merge this, even if it's not very pretty.

**Comment by dzimine** [comment]
yes.

**Pull request merged**
