### PR TITLE
Exclude execution results from the list view

### PR DESCRIPTION
**Pull request by enykeev**
Related to stackstorm/st2#1212

### CODE REVIEW

**Comment by Kami** [comment]
Just a note to us - we need to merge this into `master` and `v0.8` when the st2 changes have been merged.

**Comment by dzimine** [comment]
did this help accelerate getting action list by any chance?

**Comment by manasdk** [comment]
@dzimine I doubt this has any impact on the Actions page.

**Comment by dzimine** [comment]
indeed what I am smoking it's a history page.

**Pull request merged**
