### PR TITLE
adding re:amaze KB widget to st2web

### PR DESCRIPTION
**Pull request by jfryman**
This PR adds the necessary bits to get the re:Amaze KB tool loaded and ready to go during day-to-day usage.

/cc @enykeev - keep me honest, here. :)

### CODE REVIEW

**Comment by enykeev** [comment]
Don't see it in UI. And you also didn't remove our old "report bug" button. Will take a closer look after I'm done with the rest.

**Comment by emedvedev** [comment]
Works well. Merging.

Would be nice if we could default the KB search to the "web" section automatically, maybe. Not sure.

**Comment by enykeev** [comment]
no, it won't. We've a number of issues in this repo that doesn't belong to st2web rather st2 or some other component and only end up here because we default to this repo when reporting an error in UI.

**Comment by emedvedev** [comment]
I was only referring to the Knowledge Base search, not sending a support request, but I see your point. :)

**Comment by jfryman** [comment]
:bow:

**Pull request merged**
