### PR TITLE
Showing UUID of execution

### PR DESCRIPTION
**Pull request by emedvedev**
We have to show execution ID and preferably one-click copy it.

Copying is not possible without Flash, but the alternative is putting UUID in a text input and selecting it on click. You’ll still have to press “Cmd + C”, but everything else is done for you. A solid alternative, I think.

### CODE REVIEW

**Comment by emedvedev** [comment]
Also, had to merge action-output (#196) here, because otherwise there's really no place for the ID to go.

**Comment by enykeev** [comment]
I don't really like the visual and I think something like that would look much better. 

Saying that, the rest LGTM.

**Comment by enykeev** [comment]
Oh yeah, and I think you forgot to commit index.html. It generates just for convenience, the repository still should include the latest version.

**Comment by emedvedev** [comment]
That's exactly why I didn't. Ok, I'll commit the latest.

Re visuals: feels a little bulky this way, doesn't it? I can use it, but I haven't seen it anywhere in the UI. Where's your screenshot from?

**Comment by enykeev** [comment]
This is execution details from the execution triggered by the rule

**Comment by emedvedev** [comment]
screenshot 2015-08-27 14 29 54
@dzimine @gmedrano @DoriftoShoes Want your feedback on this. Is the visual good? Is it easy to use? Aside from feedback on visuals, ready to merge.

**Comment by Kami** [comment]
Aren't there some libraries which use new HTML 5 API for copying to clipboard and only fall back to Flash if that feature is not available?

In any case, it's not a big deal.

**Comment by emedvedev** [comment]
http://zeroclipboard.org is the most common one and it's still flash 90% of the time. I wouldn't recommend it

**Comment by emedvedev** [comment]
@manasdk gave a very vocal +1 in Slack, so I'm merging. :) Visuals can be improved later, after all.

**Comment by dzimine** [comment]
@dzimine @gmedrano @DoriftoShoes Want your feedback on this. Is the visual good?
1) ways too sparse vertically, make them dense (1.0 interval) - else the rest of the info goes away from the view. 
2) rename `s` to `seconds`. 
Other than that - good.

**Comment by manasdk** [comment]
> rename s to seconds. 
Meh. I like s/ms etc.

**Comment by dzimine** [comment]
ok :) you get it. at least have a space `8 s` not `8s`

**Comment by emedvedev** [comment]
@dzimine 
1. It's the same stylesheet as in execution triggered by the rule; should I make both more dense? If one's dense and another isn't, we lose consistency, that's not very good.
2. Added a space. :)

**Pull request merged**
