### PR TITLE
Bug/validate array of obj

### LINKED ISSUE #710: Bug: Array of type object not validating
If an action has the following for a parameter type in an action:
```yaml
parameters:
  test_array_obj:
    type: array
    items:
      type: object
    description: "array of objects to evaluate"
    required: true
    position: 0
```
There is an issue with the UI where I cannot enter an array of objects into the parameter field.
image

I've tried many permutations on how to enter the array of objects, but the UI cannot evaluate it correctly.

## Installed Versions
st2.x86_64                         2.10.1-1               @StackStorm_stable
st2-auth-ldap.x86_64               2.10.4-1               @StackStorm_enterprise
st2chatops.x86_64                  2.10.1-1               @StackStorm_stable
st2flow.x86_64                     2.10.4-1               @StackStorm_enterprise
st2mistral.x86_64                  2.10.1-1               @StackStorm_stable

## Distro 
CentOS 7

### PR DESCRIPTION
**Pull request by jdmeyer3**
This PR deals with #710 where if a form has the datatype "array of objects" it would never validate it. It also deals with the string mutation of an array of objects, causing any entered array of objects to be mutated to [object Object].

It also deals with issues from #711 where the spec may not define what kind of items an array may not have.

Closes #710
Closes #863

### CODE REVIEW

**Comment by jdmeyer3** [comment]
@LindsayHill Is the circleci issue on my end?
```
#!/bin/bash -eo pipefail
PKG_VERSION=$(node -e "console.log(require('./package.json').st2_version);")
PKG_RELEASE=$(packagecloud.sh next-revision trusty ${PKG_VERSION} st2web)
echo "export PKG_VERSION=${PKG_VERSION}" >> $BASH_ENV
echo "export PKG_RELEASE=${PKG_RELEASE}" >> $BASH_ENV
/home/circleci/scripts/packagecloud.sh: line 23: PACKAGECLOUD_TOKEN:  PACKAGECLOUD_TOKEN env is required
Exited with code 1
```

**Comment by LindsayHill** [comment]
Nah, that’s not on your end. Will have to see if there’s some way of handling that situation. It’s related to “who can see these private tokens - should PRs from forks be able to use them?”

**Comment by jdmeyer3** [comment]
@LindsayHill Has there been any progress on the Circle CI?

**Comment by LindsayHill** [comment]
@jdmeyer3 sorry, haven't had a chance to look at it. You _should_ be able to run the unit tests locally, following roughly the steps up to here https://github.com/StackStorm/st2web/blob/master/.circleci/config.yml#L59

Are those passing?

**Review by mickmcgrath13 — APPROVED** [review]
did not test locally, but syntactically, things look good

**Pull request merged**
