### PR TITLE
Axios and urijs package version updated

### PR DESCRIPTION
**Pull request by shital-orchestral**
Axios package version updated to 0.21.1 and urijs to 1.19.4.
Thanks

### CODE REVIEW

**Comment by blag** [comment]
@shital-orchestral Thank you for the contribution, but this breaks tests. Can you fix those?

**Review by armab — APPROVED** [review]
Nice one!

Thanks @shital-orchestral for the fix :+1:

**Review by m4dcoder — APPROVED** [review]
Great job!

**Comment by armab** [comment]
@shital-orchestral @m4dcoder Looks like `yarn.lock` still includes the old version here:
https://github.com/StackStorm/st2web/blob/master/yarn.lock

Can you elaborate why it's still an old version and how that plays in the build?

**Pull request merged**
