### PR TITLE
Update st2web prod dependencies

### PR DESCRIPTION
**Pull request by amanda11**

### CODE REVIEW

**Comment by amanda11** [comment]
Not ready for review - will selectively update dependencies and perform manual tests, to see which can update easily.

**Review by blag — APPROVED** [review]
I just quickly skimmed this, but it LGTM.

I'm not a Node or JS expert though, so it would be good to get another review.

**Review by m4dcoder — APPROVED** [review]
LGTM. This is just update to dependencies. I assume some basic testing has occurred and nothing broke on the UI.

**Comment by amanda11** [comment]
Yes, testing from the general release process for st2web ran successfully.

**Pull request merged**
