### PR TITLE
Remove auth tokens from query params and allow redefine Stream url 

### PR DESCRIPTION
**Pull request by enykeev**
Requires https://github.com/StackStorm/st2/pull/3566

### CODE REVIEW

**Comment by enykeev** [comment]
Ok, as a result of miscalculation on my part, this PR gets (at the very least) delayed.

The problem is that by default browsers refuse to accept cookies received cross-origin. While in theory we can solve this problem by redirecting user to the proper origin during authentication routine, it would create a fiddly user experience and may introduce other security-related problems potentially more dangerous than the one we're currently trying to fix.

**Comment by christopherjbaker** [comment]
@enykeev Does this apply to the new react UI? And, if so, should we open an issue to fix it, as I assume the changes here certainly don't apply.

**Comment by enykeev** [comment]
Yes, this change needs to be transitioned manually. Problem is, even though I've implemented it, I'm still not sure if this is the right way to handle the problem. Replacing query parameter with cookie opens us up to XSS and makes it so much more important to properly configure CORS. And if there's one thing this project taught me over the years, it that people simply don't get CORS and there's no amount of explaining or hand holding that can make up for it being poorly designed to begin with.

**Comment by enykeev** [comment]
Re-implemented as a part of #530.

**Pull request closed without merging**
