### PR TITLE
Get rid of static folder

### PR DESCRIPTION
**Pull request by enykeev**

### CODE REVIEW

**Comment by armab** [comment]
Just FYI changes needed with this edit, to make sure everything is in consistent state: 
[ ] Cherry pick this change in `st2web `
[ ] Update [nginx config](https://github.com/StackStorm/st2/blob/master/conf/nginx/st2.conf) in `st2 master`
[ ] Update [nginx config](https://github.com/StackStorm/st2/blob/v1.3.3/conf/nginx/st2.conf) in `st2` `v.1.3.3`
[ ] Ask to include
[ ] Merge everything in one `go`, making sure that both `stable` and `unstable` for `st2web` and `st2` packages were regenerated

**Comment by enykeev** [comment]
- [ ] Merge and cherry pick https://github.com/StackStorm/st2flow/pull/92

Also, are we sure that cherry-picking this stuff into stable branch won't affect our current AIO users?

Just in case, cc @lakshmi-kannan

**Comment by enykeev** [comment]
@dzimine @lakshmi-kannan so what have you decided? Are we merging it? Are we going to backport it 1.3? Or are we going to postpone it until release of 1.4 and merge it the last moment?

**Comment by lakshmi-kannan** [comment]
Looks good. I'd like to ship this with 1.3 personally. But I think we might have two folders /opt/stackstorm/static and /opt/stackstorm/webui if we don't remove the former from a step in packaging.

**Comment by enykeev** [comment]
@lakshmi-kannan I've checked and the only thing that's left in old `/opt/stackstorm/static` folder is config which we should probably keep for the reasons of karma. Other than that, it seems like dpkg handles upgrade just fine

```
vagrant@st2packages-u14:~$ tree /opt/stackstorm/{webui,static}
/opt/stackstorm/webui
├── config.js
├── css
│   └── style.css
├── favicon.ico
├── font
│   ├── animation.css
│   ├── ststanley-codes.css
│   ├── ststanley.css
│   ├── ststanley-embedded.css
│   ├── ststanley.eot
│   ├── ststanley-ie7-codes.css
│   ├── ststanley-ie7.css
│   ├── ststanley.svg
│   ├── ststanley.ttf
│   └── ststanley.woff
├── img
│   └── logo.svg
├── index.html
└── js
    ├── components.js
    ├── modules.js
    └── templates.js
/opt/stackstorm/static
└── webui
    └── config.js
```

**Comment by lakshmi-kannan** [comment]
That's cool. Please get this merged to master as well as 1.3 please.

**Comment by dzimine** [comment]
> Also, are we sure that cherry-picking this stuff into stable branch won't affect our current AIO users?
What about "new 1.3 AIO users"? I think we are not sure. And if AIO breaks in 1.3 we will need to fix it, see "deprecating AIO" plan. Proceed with care.

**Comment by lakshmi-kannan** [comment]
Hmm. Should we merge this to master now? AIO is deprecated.

**Comment by christopherjbaker** [comment]
@enykeev Does this still apply?

**Comment by enykeev** [comment]
I'd say that there's no particular reason to implement it now. It was on Dmitri's list once, but it seemingly slipped through the cracks and no one brought it up again ever since.

**Pull request closed without merging**
