### PR TITLE
Cancel execution

### PR DESCRIPTION
**Pull request by enykeev**
Adds a button allowing user to cancel ongoing execution using UI instead of switching to CLI.

### CODE REVIEW

**Comment by enykeev** [comment]
Depends on https://github.com/StackStorm/st2client.js/pull/48

**Comment by Kami** [comment]
LGTM :+1: 

Just curious - how do we indicate canceled executions in the ui? And I assume we have a live update so as soon as you press cancel execution transitions to this state? (Yeah, I know, I could just clone it and try it out myself :P)

**Comment by enykeev** [comment]
> how do we indicate canceled executions in the ui
It simply receives a live update with `canceled` status represented by the gray dot in the UI itself.

**Comment by enykeev** [comment]
:+1:

**Comment by enykeev** [comment]
:\+1:

**Pull request merged**
