### PR TITLE
fix lerna version

### PR DESCRIPTION
**Pull request by guzzijones**
fix the lerna version so the build continues

### CODE REVIEW

**Comment by guzzijones** [comment]
looks like docker needs a restart on that [circleci vm](https://github.com/docker/compose/issues/3633)  ?

**Comment by enykeev** [comment]
@guzzijones we've seen similar problems in other projects relying on docker registry and so far the only thing that had any effect is to try and restart the job some time later. Two weeks should be plenty enough for any kind of networking issues to resolve. There's plenty of other suggestions on the internet to try logging out of docker and logging back in, but they sound awfully like just trying all the options under the sun.

Do you want to try and restart this job again to see if anything has changed?

**Comment by armab** [comment]
Thanks @enykeev and good to see you! 👍 

I just pushed a dummy commit to @guzzijones fork to rebuild it (CircleCI seems to not allow GH-based login anymore) and it failed in a later step: https://app.circleci.com/pipelines/github/StackStorm/st2web/3867/workflows/b15c3ceb-1ca1-4d6c-9fd7-8b678b2584d8/jobs/6170?invite=true#step-119-1823_20

Looks like `lerna` should be pinned in more places:
https://github.com/StackStorm/st2web/blob/73e75f6632471595c42081e912372ad456caaffc/Makefile#L15

@guzzijones can you update it, or perhaps @enykeev want to try in a brand new PR? We'll need more involved dependency updates anyway.

**Comment by enykeev** [comment]
@armab I'll try to have a look on the weekend and see if if I can figure out what's wrong. That is if your efforts will not succeed. I will however need you to add me to maintainers so I can rerun CI runs at will.

**Review by armab — APPROVED** [review]
Thanks @guzzijones for the fix and @enykeev for bumping this.

**Comment by armab** [comment]
@enykeev I had to push some dummy commits to @guzzijones fork as CircleCI re-build and access rights are terribly broken (I got 404s and 50Xs myself even for the CircleCI builds in the org https://github.com/StackStorm/st2web/assets/1533818/25fc89c0-cb53-4d46-bb50-c7055caf92ad). If you could work on your fork, - the builds could be restarted OK.

The real work, - we'll need an overall renovation, audit and updating the dependencies + nodejs and whatnot for `st2web` (example, see: https://github.com/StackStorm/st2web/pulls/app%2Fdependabot) and `st2chatops` (more severe). I'll ask for temporary access rights from the [TSC](https://github.com/StackStorm/st2/blob/master/OWNERS.md) for this work if we'll hit a roadblock.
@enykeev Could you please join us in Slack (#tsc channel in https://stackstorm.com/#community)?

**Pull request merged**
