### PR TITLE
RFR: Use ref to handle rules as opposed to id

### PR DESCRIPTION
**Pull request by lakshmi-kannan**
Dependent on https://github.com/StackStorm/st2/pull/1367

I hope I caught all the `id` to ref changes for the `rules`.

### CODE REVIEW

**Comment by lakshmi-kannan** [comment]
I have no idea how we the UI works with rules without this PR :). 
cc: @enykeev

**Comment by Kami** [comment]
@lakshmi-kannan IIRC, You can also use ID (or ref) when working with rules endpoint so it should probably also work with the ID, right?

**Comment by lakshmi-kannan** [comment]
@Kami You are right but @enykeev suggested I switch to ref. I don't remember why. I am just surprised this hasn't been merged :P.

**Comment by Kami** [comment]
It's fine, I think ref is better as well :)

**Comment by manasdk** [comment]
Why is `ref` better than `id`? AFAICT there is an index on `id` and none for `ref` so it should be better to use `id` if available.

**Comment by Kami** [comment]
@manasdk It's more user-friendly and consistent with other views (e.g. actions).

And with user-friendly I mean when it's used inside the URL when retrieving details for a single rule. Besides the URL, I don't care and I'm also fine with using ID internally in other places.

**Comment by Kami** [comment]
Also, re index - there will be index once my rbac branch is done and we merged it (I've updated all the resource models to explicitly store "ref" in the DB and added index on it).

**Comment by enykeev** [comment]
I've rebased it locally and it seems like the code is still perfectly valid. Merging.

**Pull request merged**
