### PR TITLE
Error notifications

### PR DESCRIPTION
**Pull request by alex-shnayder**
Errors that were only displayed in the console now also show a notification popup.

### CODE REVIEW

**Comment by enykeev** [comment]
I've spent unpleasant amount of time trying to figure out how to mock suitable responses with `mitmproxy` before I understood I simply wasting my time.

This thing works. It doesn't look especially in style with the rest. It is particularly annoying that the left edge blends with the edge of list view. It may have problems with plaintext responses (though we mostly eliminated them anyway).

It is probably ok to merge this thing and figure out how to properly test and style it later.

**Comment by emedvedev** [comment]
@alex-shnayder can you do minor style adjustments? I'd appreciate it looking a bit more consistent, too. Everything else is good.

**Comment by alex-shnayder** [comment]
Tried to improve the looks a bit, not sure if it's any better. Also, access control needs much more thinking.

/cc @enykeev @emedvedev

**Comment by emedvedev** [comment]
Better, merging. We do need to provide better messages for RBAC scenarios, but that's a subject for another PR.

**Pull request merged**
