### PR TITLE
Update README to include steps used in build to prevent blank workflow in dev mode

### LINKED ISSUE #856: A simple solution about blank workflow pages and console errors
According to https://github.com/StackStorm/st2web/pull/799
Remove the node_modules from app/st2-workflows that is auto-generated by learn. This causes conflict which result in st2flow UI coming out as blank screen.
And the error is like this:
```
Uncaught Invariant Violation: Could not find "store" in the context of "Connect(Workflows)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(Workflows) in connect options.
    at invariant (http://192.168.126.1:3000/js/main.js:91109:15)
    at Connect.renderWrappedComponent (http://192.168.126.1:3000/js/main.js:27998:32)
    at Connect.indirectRenderWrappedComponent (http://192.168.126.1:3000/js/main.js:27994:21)
    at updateContextConsumer (http://192.168.126.1:3000/js/main.js:145757:19)
    at beginWork (http://192.168.126.1:3000/js/main.js:145945:14)
    at performUnitOfWork (http://192.168.126.1:3000/js/main.js:149585:12)
    at workLoop (http://192.168.126.1:3000/js/main.js:149625:24)
    at HTMLUnknownElement.callCallback (http://192.168.126.1:3000/js/main.js:130422:14)
    at Xa.h (AdGuard%20Popup%20Blocker.user.js:436:174)
    at nc (AdGuard%20Popup%20Blocker.user.js:454:1035)
react-dom.development.js:17117 The above error occurred in the <Context.Consumer> component:
    in Connect(Workflows) (created by Router)
    in Router (created by ConnectFunction)
    in ConnectFunction
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:17117
react-dom.development.js:20312 Uncaught Invariant Violation: Could not find "store" in the context of "Connect(Workflows)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(Workflows) in connect options.
    at invariant (http://192.168.126.1:3000/js/main.js:91109:15)
    at Connect.renderWrappedComponent (http://192.168.126.1:3000/js/main.js:27998:32)
    at Connect.indirectRenderWrappedComponent (http://192.168.126.1:3000/js/main.js:27994:21)
    at updateContextConsumer (http://192.168.126.1:3000/js/main.js:145757:19)
    at beginWork (http://192.168.126.1:3000/js/main.js:145945:14)
    at performUnitOfWork (http://192.168.126.1:3000/js/main.js:149585:12)
    at workLoop (http://192.168.126.1:3000/js/main.js:149625:24)
    at renderRoot (http://192.168.126.1:3000/js/main.js:149708:7)
    at performWorkOnRoot (http://192.168.126.1:3000/js/main.js:150615:7)
    at performWork (http://192.168.126.1:3000/js/main.js:150527:7)
```

After `lerna bootstrap`, I must **delete "apps/st2-workflows/node_modules"**. Then `gulp` will work. But I don't know why and how to solve it completely.

So updating the Quick Start tutorial in README will be more kindly.

### PR DESCRIPTION
**Pull request by amanda11**
Resolves #856

### CODE REVIEW

**Comment by amanda11** [comment]
Came across this problem when running st2web during development process, updated README as per the information suggested in #856.

**Review by cognifloyd — APPROVED** [review]
I don't know much about lerna. If that's what needs to happen then cool. Bring on the docs!

**Comment by amanda11** [comment]
> I don't know much about lerna. If that's what needs to happen then cool. Bring on the docs!

Nor do I - but its exactly what we do when we do the build process and it definitely solved my problem!

**Review by armab — APPROVED** [review]
:+1:

**Pull request merged**
